In [2]:
import numpy as np

In [3]:
arr=np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# on veut selectionner un element precis. Par exemple 6
# array[index] et ici l'indexe de 6 est 6

arr[6]

6

In [14]:
# on peut egalement selectionner plusieurs en donnant l'indice de depart et celui de l'arrivé
# array[start: end] avec 'end' exclut

arr[2: 6] # dans [2, 6[

array([2, 3, 4, 5])

In [15]:
# par defaut si on ajoute rien au debut, c,est '0'
# array[: end] avec 'end' exclut

arr[:6] # dans [0, 6[

array([0, 1, 2, 3, 4, 5])

In [17]:
# par defaut si on ajoute rien a la fin, il considere le dernier indice ( ici 10)
# array[start:]

arr[2: ] # dans [2, 11[ ou [2, 10] parce que on a 10 index

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# par logique si on veut donc selectionner tous les elements de notre tableau
# array[:]

arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# concept de diffusion BroadCasting

arr[0: 5]=100 # alors aux indices compris dans [0, 5[, on aura 100 si on affiche

In [20]:
# affichage apres modification
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
# reinitialisation de vers notre tableau originel

arr=np.arange(11)

In [28]:
# on peut utiliser des parts de notre tableau

slice_of_arr=arr[0: 5] # 0n selctionne les elements dont les indices sont dans [0, 5[

In [29]:
# affichage

slice_of_arr

array([0, 1, 2, 3, 4])

In [33]:
slice_of_arr[:] # cela signifie que notre tableau 'slice_of_arr' est bien definie

array([0, 1, 2, 3, 4])

In [34]:
slice_of_arr[:]=99 # on attribut à tous ses index la valeur 99

In [35]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [37]:
# et maintenant si on retourne vers notre tableau originel
arr

# on verra que la partie delectionné sera celle qui a ete modifié

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [38]:
# pour eviter le probleme ci dessus, cad ne pas modifier la valeur de notre tableau originel ,
# on peut créer tous simplement une copie avec 'copy()' et y apporter nos modification

arr_copy=arr.copy()

In [39]:
# affichage

arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [40]:
# on peut le modifier
arr_copy[:]=100

In [41]:
# affichage
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [43]:
# affichage tableau originel

arr

# aucune modification

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [46]:
# indexation sur les matrices

arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]]) #matrice de dimension 2

In [47]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# pour l,indexation c'est pareil, sauf que on va devoir preciser la ligne et la colonne
# index 0= ligne
# index 1= colonne

# si on veut voir combien de ligne et colone on a , on peut utiliser shape

arr_2d.shape

# 3lines, 3colonnes

(3, 3)

In [55]:
# index 0= ligne
# index 1= colonne

arr_2d[0] # premiere ligne

# arr_2d[1] # 2eme ligne
# arr_2d[2] # 3eme ligne

array([1, 2, 3])

In [57]:
# supposons mainteant qu'on aimerait avoir exactement 1 element
# il va falloir ajouter sa ligne et sa colonne simplement soit 'array[line, colonne]' soit 'array[line][colone]'
# par exemple si on veut 5, cest 2eme ligne (line =1) et 2eme colonne(colonne=1)

arr_2d[1][1]

5

In [58]:
# avec l'autre notation si on veut 7

arr_2d[2,0]

7

In [59]:
# on peut selectionner un groupe dans notre matrice

arr_2d[:2] # on prend les elements dans [0,2[ soit ceux de 0 et 1

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr_2d[:2, 0:2] # on ajoute les colonnes egalement afin d'etre plus precis

array([[1, 2],
       [4, 5]])

In [62]:
# Selection conditionnelle

# on va selectionner les elements d'un tableau en se basant sur une condition

# initialisation d'in nouveau tableau

arrN=np.arange(1,11)

In [66]:
arrN

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
# on veut les valeurs superieur a 4.
# le resultat ici sera sous forme du tableau avec des booleans

arrN>4 # les indices prendront la place des booleans

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
bool_arr=arrN>4

In [72]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
arrN[bool_arr] # et biensur il va afficher les elements suivant la condition de bool_arr

array([ 5,  6,  7,  8,  9, 10])

In [76]:
# on aurait egalement pu le faire de facon tres simple au lieu de passer par une variable intermediaire

arrN[arrN>4]

array([ 5,  6,  7,  8,  9, 10])