In [1]:
import numpy as np

In [4]:
# creation de liste banale

myList=[1,2,3,4,5]

In [3]:
#conversion de myList en tableau NumPy

np.array(myList)

array([1, 2, 3, 4, 5])

In [6]:
# liste imbriquée

NestedList=[[1,2],['a','b'],[5,6]]

In [7]:
# conversion de liste imbriquée

np.array(NestedList)

array([['1', '2'],
       ['a', 'b'],
       ['5', '6']], dtype='<U21')

In [10]:
#'arange(debut, fin, pas)' se comporte comme range() en python. 'pas' est par defaut 1

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# par exemple les nombres paires de 2 à 20

np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# par exemple ici on evolut de 2 en 2 a partir de et on inclut 20

np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
# c'est pratique d'avoir un tableau contenant que des 0 ou que des 1
# avec NumPy, on utilise '.zeros((nbLigne, nbColumns), dtype=float)' : par defaut

np.zeros(5) # par defaut 1 ligne, donc ici 5 colonnes que de 1

# NB : a part 'arange', toutes les autres methodes vont convertir en float. d'ou : 0., 0.

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5, 10))

# Matrice de dimension 2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
# Si on veut avoir une sortie qui n'est pas de type float, alors il faut le preciser via 'dtype=int' : pour entier

np.zeros((5, 10), dtype=int)

# Matrice de dimension 2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
# Si on veut que des 1 a la place des 0

np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [20]:
# '.linspace(start, stop, num)' : fonction de la biblio de NumPy qui permet d'epacer ou diviser unformement l'intervalle [start, stop]

np.linspace(0, 10, 2) # on veut obtenir 2 nombres dans [0, 10] uniformenent

# Naturellement la sortie est de type float

array([ 0., 10.])

In [21]:
np.linspace(0, 10, 10) # on veut obtenir 10 nombres dans l'intervalle [0, 10] uniformement

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
# Supposons que on veut la meme sortie du dessu, mais avec des resultats fractionnel, cad pas avec autant de nombres apres la virgule
# Dans ce cas , il faudra ajouter 1 à notre nombre 'stop'

np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# Pour mieux visualiser

print(' Sans forme fractionnelle :\n')
np.linspace(0, 10, 20)
print(' Avec forme fractionnelle :\n')
np.linspace(0, 10, 21)

 Sans forme fractionnelle :

 Avec forme fractionnelle :



array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [24]:
# Matrice identité (matrice carrée dont la diagonale est 1 et les autres elements 0)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# on peut generer aleatoirement des nombre flottant biensur dans des matrices selon la loi uniforme
# cad nos valeur sont uniformement repartie

np.random.rand(3) # genere 3 nombre flottant uniformement reparti

array([0.46436355, 0.23122337, 0.99843651])

In [26]:
# random.rand(line, columns)

np.random.rand(3, 4)

array([[0.87139831, 0.68611804, 0.53153586, 0.13384246],
       [0.48344986, 0.89771973, 0.14226844, 0.33790551],
       [0.64671942, 0.45244193, 0.30943017, 0.91523014]])

In [117]:
# distribution normal standard
# moyenne=0 (centré sur 0), variance=1
# genere des nombres negatifs compris entre -1 et 1, et biensur des nombres positifs à partir de 0

np.random.randn(4, 4)

array([[ 0.42448624,  0.94053558, -0.86764109,  0.14586185],
       [-1.36987106, -0.77178075,  0.87867355, -0.23959451],
       [ 1.20938197,  0.53796   ,  2.73442216,  0.09376543],
       [-1.40640527, -0.03452966, -0.96301563,  0.97718   ]])

In [28]:
# generer aleatoirement un nombre a partir de l'intervalle [a, b], avec a inclu et b pas inclu

np.random.randint(0, 100) # 0 peut etre selectionné, mais jamais 100

9

In [29]:
# on veut maintenant preciser le nombre n d'element que on veut recuperer : .randint(a, b, n)

np.random.randint(0, 101, 20) # On recupere 20 elements avec 100 inclut et 101 exclut

array([ 18,  30,  69,   7,  68,  65,   6,  27,  59,   4,  94,  58,  33,
        25,  83, 100,  64,  43,  65,  88])

In [30]:
# Mais on peut aussi faire afficher nos nombres dans un tableau matricielle (x_line, y_colone): .randint(a, b, (x,y) )

np.random.randint(0, 100, (5,5)) # 5 line, 5 columns

array([[77, 10, 39, 31, 30],
       [ 1, 34, 47, 29, 10],
       [97, 53,  9,  2, 72],
       [75, 63, 94, 45, 36],
       [77, 54, 33, 24, 26]])

In [31]:
# pour reproduire les memes nombres aleatoires
# .random.seed(id_Number) : c est comme un id , pour tel id, la machine genere des nombres identique pour tous le monde

np.random.seed(42)
np.random.rand(4)

# faut toujours les executer ensembles pour que le 'seed()' puisse fixer la valeur

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
# si on execute en solo, ca ne fonctionne pas, donc faut toujours preceder cela d'un seed()
# A ce moment ici, il faut toujours executer encore une fois le code ci dessus avec le seed() afin d'avoir des valeurs aleatoire
# identique. cad on pourra garder la fonctionnalité du seed() qui genere toujours les memes variables pour tous le monde

np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [50]:
arr=np.arange(25) # par defaut start=0 et stop=24-1, genere les nombres de [0, 24[

print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [51]:
# si on veut afficher sous forme de tableau NumPy

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [96]:
randomArr=np.random.randint(0, 50, 10) #on genere 10 nombres entier dans [0, 50[

print(randomArr)

[31  8 40 34 18 47 15  2 19 23]


In [97]:
# si on veut afficher sous forme de tableau NumPy

randomArr

array([31,  8, 40, 34, 18, 47, 15,  2, 19, 23])

In [98]:
# la maximun de la serie

randomArr.max()

5

In [99]:
# la position du maximun

randomArr.argmax()

5

In [100]:
# le minimun de la serie

randomArr.min()

2

In [101]:
# la position du minimun

randomArr.argmin()

7

In [54]:
# on peut modeler la dimension de notre tableau grace a 'shape' et 'reshape'
# shape : donne la dimension actuelle
# reshape : permet de modifier la dimention actuel
# par exemple nous on a au debut dimension=1 , et on veut dimension =2

arr.shape

(25,)

In [58]:
# on veut toujour a partir de nos 25 nombres generé avoir une matrice 2X2

arr.reshape(5,5)

# NB : on ne peut pas remodeler un tableau avec des valeurs aleatoires, il faut s'assurer que ca marche avec nos nombres d'elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
# notre valeur du debut es conservé
# si on voulais qu'elle prenne celle du reshape, alors : arr=arr.reshape(5, 5)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
# on attribue une nouvelle valeur a notre randomArr

randomArr=np.random.randint(0, 20, (5, 5)) # genere 20 nombres repartie en matrice 5lines, 5colounns

In [89]:
# affichage, mais si on veut que a chaque compilation les valeurs changent, alors faut toujours compiler la ligne ci dessus avant

randomArr

array([[ 0,  8,  5, 15,  2],
       [19,  3, 18,  2, 18],
       [19,  6, 19,  8,  0],
       [ 7,  6, 17,  7,  0],
       [10, 17,  9,  2,  6]])

In [90]:
# randomVar.max() : donne le max de la chaine aleatoire
# randomMin.min() : donne le min de la chaine aleatoire

# randonArgMax.argmax() : donne la position du max, son index et on commence a compter a partir de 0 en python
# randonArgMin.argmin() : donne la position du min, son index et on commence a compter a partir de 0 en python

randomArr.max()

# NB : la valeur sera toujour la meme pour la compilation, mais si je compile la ligne ci dessus avant, alors la valeur ici change

19

In [91]:
# position de notre max

randomArr.argmax()

5

In [103]:
# on utilise l'attribut dtype pour connaitre le type de donné d'un tableau NumPy

tabAl1=np.random.randint(0, 10, 5)


In [104]:
tabAl1

array([5, 7, 0, 7, 3])

In [105]:
# type de donnée :

tabAl1.dtype

dtype('int64')

In [121]:
# si on genere des nombres selon la loi normal standard centré en 0 et de variance 1 (d'ou des nombres negatifs) :

tabAl2=np.random.randn(3, 3)

In [122]:
# affichage matrice 3lines, 3columns

tabAl2

array([[ 1.05742351,  0.05136086,  0.87244716],
       [ 1.06619854, -0.9590081 ,  1.3820046 ],
       [ 0.90512196, -0.60390437,  0.30444912]])

In [123]:
# type de donnée

tabAl2.dtype

dtype('float64')